import "./globals.css";
import type { Metadata } from "next";
import TopLayout from "@/components/TopLayout";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TopLayout />
        {children}</body>
    </html>
  );
}