// "use client";
import "./globals.css";
import type { Metadata } from "next";
import Topbar from "@/components/Topbar";
import Sidebar from "@/components/Sidebar";
import { PrimeReactProvider } from "primereact/api";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import { AppContextProvider } from "./AppContext";
import { NextAuthProvider } from "@/components/NextAuthProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <PrimeReactProvider>
      <NextAuthProvider>
        <AppContextProvider>
          <html lang="en" className="h-full">
            <body className="h-full">
              <div className="flex h-full">
                <Sidebar />
                <div className="flex flex-col flex-1 min-h-0 h-screen">
                  <Topbar />
                  <div className="flex-1 mx-7 mb-5 h-[80%]">{children}</div>
                </div>
              </div>
            </body>
          </html>
        </AppContextProvider>
      </NextAuthProvider>
    </PrimeReactProvider>
  );
}
