import { PrismaClient } from "../db/prisma";
const prisma = new PrismaClient();

const main = async () => {
  console.log("🌱 Starting to seed user data...");

  const createdDepartments = await prisma.departments.findMany();
  const createdPositions = await prisma.positions.findMany();
  const createdJobs = await prisma.jobs.findMany();
  const employeesData = [
    // 1 Trưởng Phòng
    {
      firstName: "Duy Hùng",
      lastName: "Nguyễn",
      phone: "0901234567",
      email: "duy.hung.nguyen@company.com",
      birthday: new Date("1985-03-15"),
      maritalStatus: "married",
      gender: "male",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/men/6.jpg",
      address: "147 Cách Mạng Tháng 8, P.10",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Trưởng Phòng")?.id,
      jobId: createdJobs.find((j) => j.job === "Team lead")?.id,
      startDate: new Date("2024-05-20T17:00:00"),
      type: "full-time",
    },

    // 20 Nhân Viên (10 Node JS + 10 React JS)
    {
      firstName: "Văn Minh",
      lastName: "Trần",
      phone: "0912345678",
      email: "van.minh.tran@company.com",
      birthday: new Date("1988-06-12"),
      maritalStatus: "single",
      gender: "male",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/men/23.jpg",
      address: "123 Nguyễn Huệ, Q.1",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "Node JS")?.id,
      startDate: new Date("2024-06-01T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Thị Linh",
      lastName: "Lê",
      phone: "0923456789",
      email: "thi.linh.le@company.com",
      birthday: new Date("1990-09-25"),
      maritalStatus: "married",
      gender: "female",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/women/18.jpg",
      address: "456 Lê Lợi, Q.1",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "React JS")?.id,
      startDate: new Date("2024-06-08T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Quang Đức",
      lastName: "Phạm",
      phone: "0934567890",
      email: "quang.duc.pham@company.com",
      birthday: new Date("1992-11-14"),
      maritalStatus: "single",
      gender: "male",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/men/47.jpg",
      address: "789 Võ Văn Tần, Q.3",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "Node JS")?.id,
      startDate: new Date("2024-06-15T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Thị Hương",
      lastName: "Hoàng",
      phone: "0945678901",
      email: "thi.huong.hoang@company.com",
      birthday: new Date("1989-04-08"),
      maritalStatus: "married",
      gender: "female",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/women/31.jpg",
      address: "234 Điện Biên Phủ, Q.Bình Thạnh",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "React JS")?.id,
      startDate: new Date("2024-06-22T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Minh Tuấn",
      lastName: "Vũ",
      phone: "0956789012",
      email: "minh.tuan.vu@company.com",
      birthday: new Date("1991-07-30"),
      maritalStatus: "single",
      gender: "male",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/men/65.jpg",
      address: "567 Pasteur, Q.3",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "Node JS")?.id,
      startDate: new Date("2024-07-01T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Thị Mai",
      lastName: "Đặng",
      phone: "0967890123",
      email: "thi.mai.dang@company.com",
      birthday: new Date("1993-12-18"),
      maritalStatus: "single",
      gender: "female",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/women/52.jpg",
      address: "890 Hai Bà Trưng, Q.1",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "React JS")?.id,
      startDate: new Date("2024-07-08T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Văn Thành",
      lastName: "Bùi",
      phone: "0978901234",
      email: "van.thanh.bui@company.com",
      birthday: new Date("1987-05-22"),
      maritalStatus: "married",
      gender: "male",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/men/36.jpg",
      address: "123 Cộng Hòa, Q.Tân Bình",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "Node JS")?.id,
      startDate: new Date("2024-07-15T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Thị Lan",
      lastName: "Lý",
      phone: "0989012345",
      email: "thi.lan.ly@company.com",
      birthday: new Date("1994-02-14"),
      maritalStatus: "single",
      gender: "female",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/women/27.jpg",
      address: "456 Nguyễn Trãi, Q.5",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "React JS")?.id,
      startDate: new Date("2024-07-22T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Thanh Long",
      lastName: "Trịnh",
      phone: "0990123456",
      email: "thanh.long.trinh@company.com",
      birthday: new Date("1986-10-05"),
      maritalStatus: "married",
      gender: "male",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/men/72.jpg",
      address: "789 Lê Văn Sỹ, Q.3",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "Node JS")?.id,
      startDate: new Date("2024-08-01T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Thị Oanh",
      lastName: "Ngô",
      phone: "0901234568",
      email: "thi.oanh.ngo@company.com",
      birthday: new Date("1995-08-27"),
      maritalStatus: "single",
      gender: "female",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/women/44.jpg",
      address: "234 Hoàng Sa, Q.1",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "React JS")?.id,
      startDate: new Date("2024-08-08T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Quốc Duy",
      lastName: "Dương",
      phone: "0912345679",
      email: "quoc.duy.duong@company.com",
      birthday: new Date("1988-01-19"),
      maritalStatus: "married",
      gender: "male",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/men/58.jpg",
      address: "567 Trường Sa, Q.Phú Nhuận",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "Node JS")?.id,
      startDate: new Date("2024-08-15T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Thị Thu",
      lastName: "Cao",
      phone: "0923456780",
      email: "thi.thu.cao@company.com",
      birthday: new Date("1992-06-11"),
      maritalStatus: "single",
      gender: "female",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/women/83.jpg",
      address: "890 Nguyễn Văn Cừ, Q.5",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "React JS")?.id,
      startDate: new Date("2024-08-22T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Minh Khoa",
      lastName: "Phan",
      phone: "0934567891",
      email: "minh.khoa.phan@company.com",
      birthday: new Date("1990-03-28"),
      maritalStatus: "married",
      gender: "male",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/men/14.jpg",
      address: "123 An Dương Vương, Q.5",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "Node JS")?.id,
      startDate: new Date("2024-09-01T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Thị Ngọc",
      lastName: "Võ",
      phone: "0945678902",
      email: "thi.ngoc.vo@company.com",
      birthday: new Date("1993-11-07"),
      maritalStatus: "single",
      gender: "female",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/women/69.jpg",
      address: "456 Tôn Thất Tùng, Q.1",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "React JS")?.id,
      startDate: new Date("2024-09-08T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Văn Tài",
      lastName: "Đinh",
      phone: "0956789013",
      email: "van.tai.dinh@company.com",
      birthday: new Date("1991-09-15"),
      maritalStatus: "married",
      gender: "male",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/men/81.jpg",
      address: "789 Nguyễn Đình Chiểu, Q.3",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "Node JS")?.id,
      startDate: new Date("2024-09-15T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Thị Phương",
      lastName: "Lưu",
      phone: "0967890124",
      email: "thi.phuong.luu@company.com",
      birthday: new Date("1989-12-23"),
      maritalStatus: "single",
      gender: "female",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/women/16.jpg",
      address: "234 Nguyễn Thị Minh Khai, Q.3",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "React JS")?.id,
      startDate: new Date("2024-09-22T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Quang Vinh",
      lastName: "Hồ",
      phone: "0978901235",
      email: "quang.vinh.ho@company.com",
      birthday: new Date("1987-04-16"),
      maritalStatus: "married",
      gender: "male",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/men/26.jpg",
      address: "567 Lý Tự Trọng, Q.1",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "Node JS")?.id,
      startDate: new Date("2024-10-01T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Thị Hạnh",
      lastName: "Tạ",
      phone: "0989012346",
      email: "thi.hanh.ta@company.com",
      birthday: new Date("1994-07-03"),
      maritalStatus: "single",
      gender: "female",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/women/75.jpg",
      address: "890 Nam Kỳ Khởi Nghĩa, Q.3",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "React JS")?.id,
      startDate: new Date("2024-10-08T17:00:00"),
      type: "full-time",
    },
    {
      firstName: "Văn Đạt",
      lastName: "Mai",
      phone: "0990123457",
      email: "van.dat.mai@company.com",
      birthday: new Date("1986-11-20"),
      maritalStatus: "married",
      gender: "male",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/men/49.jpg",
      address: "123 Trần Hưng Đạo, Q.1",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Nhân Viên")?.id,
      jobId: createdJobs.find((j) => j.job === "Node JS")?.id,
      startDate: new Date("2024-10-15T17:00:00"),
      type: "full-time",
    },

    // 2 Thực Tập Sinh
    {
      firstName: "Văn Nam",
      lastName: "Chu",
      phone: "0901234569",
      email: "van.nam.chu@company.com",
      birthday: new Date("2001-05-14"),
      maritalStatus: "single",
      gender: "male",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/men/33.jpg",
      address: "456 Đinh Tiên Hoàng, Q.1",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Thực Tập")?.id,
      jobId: createdJobs.find((j) => j.job === "React JS")?.id,
      startDate: new Date("2024-11-01T17:00:00"),
      type: "part-time",
    },
    {
      firstName: "Thị Linh",
      lastName: "Hà",
      phone: "0912345680",
      email: "thi.linh.ha@company.com",
      birthday: new Date("2002-03-08"),
      maritalStatus: "single",
      gender: "female",
      nationality: "Việt Nam",
      image: "https://randomuser.me/api/portraits/women/12.jpg",
      address: "789 Hoàng Văn Thụ, Q.Tân Bình",
      city: "Hồ Chí Minh",
      state: "Hồ Chí Minh",
      status: "Active",
      departmentId: createdDepartments.find(
        (d) => d.name === "Phát triển sản phẩm"
      )?.id,
      positionId: createdPositions.find((p) => p.title === "Thực Tập")?.id,
      jobId: createdJobs.find((j) => j.job === "Node JS")?.id,
      startDate: new Date("2024-11-08T17:00:00"),
      type: "part-time",
    },
  ];

  let createdEmployeesCount = 0;
  for (const employeeData of employeesData) {
    try {
      await prisma.employees.create({
        data: employeeData,
      });
      createdEmployeesCount++;
    } catch {
      console.log(
        `⚠️ Skipped employee ${employeeData.firstName} ${employeeData.lastName} - might already exist`
      );
    }
  }
  console.log(`✅ Created ${createdEmployeesCount} employees`);
};

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
